# ──────────────────────────────────────────────────────────────────────────────
#  smartroom_api.py
# ──────────────────────────────────────────────────────────────────────────────
"""
FastAPI service that receives a sensor payload + a free‑form voice command,
decides what the room should do (lights, colour, …) and asks Groq’s LLM to
explain the reasoning.

Key improvements over the original snippet:
*   ✅ No trailing spaces in the model name.
*   ✅ Explicit check for the GROQ_API_KEY env‑var.
*   ✅ Async‑friendly Groq call (run in a thread‑pool so the event‑loop stays free).
*   ✅ Strongly‑typed request & response models (OpenAPI docs automatically generated).
*   ✅ Robust command parsing – colour + on/off can be combined.
*   ✅ Validation of numeric fields (noise must be 0‑120 dB).
*   ✅ Centralised logging (structured, time‑stamped).
*   ✅ Automatic retries on transient HTTP errors.
*   ✅ Clear error handling – callers get a proper 4xx/5xx HTTP status, not a silent
    “status: error” dict.
"""

import os
import logging
from typing import Literal, Optional, Tuple

import anyio
import httpx
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field, conint, validator

# --------------------------------------------------------------------------- #
#   Logging configuration (feel free to customise format / level)
# --------------------------------------------------------------------------- #
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s | %(message)s",
)
log = logging.getLogger("smartroom")

# --------------------------------------------------------------------------- #
#   Environment & Groq client
# --------------------------------------------------------------------------- #
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise RuntimeError("🔑 Environment variable GROQ_API_KEY is required")

# The official Groq SDK is synchronous; we’ll call it from a thread‑pool.
# If a future version ships an async client you can replace the wrapper below.
from groq import Groq  # pip install groq

_sync_client = Groq(api_key=GROQ_API_KEY)

# --------------------------------------------------------------------------- #
#   FastAPI app
# --------------------------------------------------------------------------- #
app = FastAPI(
    title="Smart‑Room AI",
    version="1.0.0",
    description="Parse voice commands & sensor data, decide an action, and let Groq explain it.",
)

# --------------------------------------------------------------------------- #
#   Pydantic models
# --------------------------------------------------------------------------- #
class SmartRoomInput(BaseModel):
    """Payload that the front‑end/device sends."""

    motion: bool = Field(..., description="True if motion was detected in the last few seconds")
    noise: conint(ge=0, le=120) = Field(
        ..., description="Ambient noise level in dB (0‑120)"
    )
    command: str = Field(..., min_length=1, description="Free‑form voice command")

    @validator("command")
    def _strip(cls, v: str) -> str:
        """Trim whitespace; keep original case for nice LLM prompt."""
        return v.strip()


class SmartRoomOutput(BaseModel):
    """Standardised response returned to the caller."""

    status: Literal["ok", "error"]
    action: Optional[str] = Field(
        None,
        description="Machine‑readable action (e.g. lights_on, set_color_red, …). "
        "If `null` the request could not be understood.",
    )
    ai_response: Optional[str] = Field(
        None,
        description="Explanation generated by Groq’s LLM.",
    )
    detail: Optional[str] = Field(
        None,
        description="Human‑readable error message when `status` = \"error\".",
    )


# --------------------------------------------------------------------------- #
#   Helper utilities
# --------------------------------------------------------------------------- #
class ActionResult:
    """
    Tiny container used by the parser so we can return *both* a primary action
    (lights on/off) and an optional colour.  This makes it easy to later expand
    the API (e.g. “turn on the lights blue” → lights_on + set_color_blue).
    """

    def __init__(self, lights: Optional[str] = None, colour: Optional[str] = None):
        self.lights = lights          # "lights_on" | "lights_off" | None
        self.colour = colour          # "set_color_red" | … | None

    @property
    def combined(self) -> str:
        """Return a single string that downstream code can store in DB."""
        parts = [self.lights, self.colour]
        # filter out Nones and join with '+' – e.g. "lights_on+set_color_red"
        return "+".join(filter(None, parts)) or "none"


def parse_command(raw: str) -> ActionResult:
    """
    Very small rule‑based parser.  It looks for:
    *   lights on / off
    *   colour words (red, blue, …)
    The parser is case‑insensitive and tolerant of extra whitespace/punctuation.
    """
    cmd = raw.lower()

    # 1️⃣ lights on/off
    lights_action: Optional[str] = None
    if any(kw in cmd for kw in ("lights on", "turn on the lights", "light on", "illuminate")):
        lights_action = "lights_on"
    elif any(kw in cmd for kw in ("lights off", "turn off the lights", "light off", "darken")):
        lights_action = "lights_off"

    # 2️⃣ colour
    colour_map = {
        "red": "set_color_red",
        "blue": "set_color_blue",
        "green": "set_color_green",
        "purple": "set_color_purple",
        "yellow": "set_color_yellow",
        "white": "set_color_white",
        "orange": "set_color_orange",
        "pink": "set_color_pink",
    }

    colour_action: Optional[str] = None
    for word, act in colour_map.items():
        if word in cmd:
            colour_action = act
            break  # first colour match wins

    return ActionResult(lights=lights_action, colour=colour_action)


# --------------------------------------------------------------------------- #
#   Groq helper – retries + thread‑pool execution
# --------------------------------------------------------------------------- #
async def _call_groq_llm(messages: list[dict]) -> str:
    """
    Run the synchronous Groq client in a thread‑pool, with a small exponential
    back‑off on transient HTTP errors (429, 502, 503, 504).

    Returns only the generated text (or raises HTTPException on failure).
    """
    max_tries = 3
    backoff = 1.0

    async def _sync_call() -> str:
        response = _sync_client.chat.completions.create(
            model="llama3.1-8b-instant",  # ← no trailing space
            messages=messages,
        )
        # Defensive guard – the SDK should always return at least one choice.
        if not getattr(response, "choices", None):
            raise RuntimeError("Groq returned an empty response")
        return response.choices[0].message.content  # type: ignore[no-any-return]

    for attempt in range(1, max_tries + 1):
        try:
            # Run the sync call without blocking the event loop.
            return await anyio.to_thread.run_sync(_sync_call)
        except (httpx.HTTPStatusError, httpx.ConnectError) as exc:
            # 429 (rate‑limit) or any 5xx are considered retryable.
            if isinstance(exc, httpx.HTTPStatusError) and exc.response.status_code not in {
                429,
                502,
                503,
                504,
            }:
                raise HTTPException(
                    status_code=status.HTTP_502_BAD_GATEWAY,
                    detail=f"Groq API error: {exc.response.status_code}",
                )
            if attempt == max_tries:
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail="Groq service unavailable after several retries",
                )
            log.warning(
                "Groq request failed (attempt %s/%s) – retrying in %.1fs: %s",
                attempt,
                max_tries,
                backoff,
                exc,
            )
            await anyio.sleep(backoff)
            backoff *= 2  # exponential back‑off


# --------------------------------------------------------------------------- #
#   Endpoint
# --------------------------------------------------------------------------- #
@app.post(
    "/smartroom",
    response_model=SmartRoomOutput,
    status_code